# Generated by Django 2.2.7 on 2019-11-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='code',
            new_name='quesCode',
        ),
    ]
