# Generated by Django 2.2.7 on 2019-11-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20191130_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='created',
            new_name='created_on',
        ),
    ]
