# Generated by Django 2.2.7 on 2019-11-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20191130_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='successful_submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='total_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
