# Generated by Django 2.2.7 on 2019-11-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20191130_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='testCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase', models.FileField(upload_to='problem_statements/testcases')),
                ('solution', models.FileField(upload_to='problem_statements/solutions')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
        ),
    ]
