# Generated by Django 2.2.7 on 2019-12-01 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='problem_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
    ]
