# Generated by Django 2.2.7 on 2019-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_submissions_problem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='time',
            field=models.FloatField(choices=[(0.5, 0.5), (1.0, 1.0)], default=1.0),
        ),
    ]
